#!/bin/bash

echo "🧪 Axon Local Registry Testing Guide"
echo "===================================="
echo ""
echo "1️⃣  Start the registry server (in another terminal):"
echo "   cd test/registry"
echo "   go run server.go ."
echo ""
echo "2️⃣  Configure Axon:"
echo "   ./bin/axon init"
echo "   ./bin/axon registry set default http://localhost:8080"
echo ""
echo "3️⃣  Test via CLI:"
echo "   ./bin/axon search bert"
echo "   ./bin/axon info nlp/gpt2@1.0.0"
echo "   ./bin/axon install nlp/gpt2@1.0.0"
echo ""
echo "4️⃣  Test via Browser:"
echo "   Open http://localhost:8080"
echo ""
echo "📖 See test/registry/README.md for full documentation"
